// <auto-generated />
namespace VideoRentalService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seedMembershipTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seedMembershipTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202007030434394_seedMembershipTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
